- c-driver/iob-cache.c
- c-driver/iob-cache.h
- rtl/src/iob-cache.v
- rtl/testbench/iob-cache_tb.v
- rtl/testbench/iob-cache_tb.vh
- rtl/wrapper/L2_ID_1sp.v
- CTRL's selection through addr[MSB], implementations on iob-cache, wrapper and testbench; 
- c-drive changed for an working state, now ctrl functions are .c functions, needs to find a better solution to avoid using the stack.
- Small fixes for Vivado synthesis.
> CTRL's selection through addr[MSB]; c-drive rolled back for working state.

- rtl/src/iob-cache.v
- simulation/icarus/Makefile
- Fixed Quartus synthesis error 10644, which is fixable by merely adding labels/names to the for-loop generates.
source: https://stackoverflow.com/questions/33899691/instantiate-modules-in-generate-for-loop-in-verilog
> Quartus Error 10644 fix - Added labels to for-loop generates

- hardware/src/front-end.v
- hardware/src/iob-cache.v
Completed the structure for:
- iob-cache: top level, for both native and AXI back-ends.
- front-end: stores the input data; asserts ready at the end of the request; selects the read-data (if controller is implemented).
Submodules updated.
> IOb-cache (top: Native; AXI) and Front-end modules completed

- hardware/fpga/AES-KU040-DB-G/Makefile
- hardware/fpga/AES-KU040-DB-G/synth.tcl
- hardware/hardware.mk
- hardware/src/back-end-native.v
- hardware/src/cache-memory.v
- hardware/src/iob-cache.v
- hardware/testbench/pipeline-iob-cache_tb.v
- Previous FIFO would take longer to deassert "empty" resulting in a read after a write-miss to start the line-replacement before the data was written to the back-memory.
- Changed to sync-fifo.
- small bugfixing and synth.tcl improvements
> Write-miss -> Line replacement issue fix

- hardware/src/back-end-native.v
- hardware/src/cache-memory.v
- hardware/src/front-end.v
- hardware/src/iob-cache.v
There are 2 warnings that currently are unfixable:
Front-end - Unconnected ports:
- ctrl_rdata and ctrl_ready. This 2 signals from cache-control are inputs in the front-end, but aren't usuable in the front-end if it isn't implemented (CTRL_CACHE(0)). 
Changed back-end Native interface so it will work correctly with the L2 cache, avoiding repeated tasks (valid deasserts when receiving the (last) ready);
Fixed latching issues.
> Fixing synthesis warnings; Changed back-end native transfers to allow the correct use of L2

- hardware/simulation/iob-cache-gtkwave.gtkw
- hardware/src/cache-memory.v
- hardware/testbench/pipeline-iob-cache_tb.v
- In this new RAW prevention, only if the index, offset, and way are the same, the stall occurs.
> Optimized RAW prevention: only prevents same positon access

- hardware/src/cache-memory.v
- hardware/src/iob-cache-axi.v
- hardware/src/iob-cache.v
- hardware/testbench/iob-cache_tb.vh
- Cache-memory (cache_memory.v) has all the available configurations for N_WAYS and LINE2MEM_W paramaters.
- For LINE2MEM_W = 0 may require some optimization, as synthesis results resulted in an unwanted increase in LUTs (around 200, need to check the reason (was expecting around the same or even less (the only difference is that the back-end write-channel has MUX to align both wdata and wstrb, but the remaining logic in the read-channel and in cache-memory gets simpler)).
> Added all available configurations for cache-memory

- hardware/src/cache-memory.v
Fixed RAW problem (less optimal though): L2 dhrystone (8KB) 100 runs CPI 1,284 to 1,330 (but without artifacts in printfs).
Working in multiple different configurations without any issue.
L1-ID are artifactless, though sometimes only prints part of the number of the number of cycles (didn't seem to be a iob-cache issue). Works will multiple configurations.
Works on both -0s and -03. From low number of Dhrystone runs to high (up to 1000)
> RAW important (temporary) fix

- software/iob-cache.c
- software/iob-cache.h
- control instructions memory mapping is now the same as the hardware mapping
- cache_base initialization requires base_address so that iob-soc addresses the external memory to begin with
> Fixes to cache control by software

- hardware/include/iob-cache.vh
- hardware/simulation/iob-cache-gtkwave.gtkw
- hardware/src/cache-control.v
- hardware/src/cache-memory.v
- hardware/src/iob-cache-axi.v
- hardware/src/iob-cache.v
- hardware/testbench/iob-cache_tb.vh
- hardware/testbench/pipeline-iob-cache_tb.v
RAW optimization in Cache-memory: only forces a delay in case the read-access is for the same offset and way (same block-ram). 
Fixed Cache-memory bugs:
- Correct implementation of optimized RAW prevention in the 4 available configurations;
- Correct implementation of hits and misses for Cache-Control.
Implementation of Cache-Control. Available for both with and without counters (hit-misses and access-types).
Submodules updated.
> Cache-memory optimization (RAW) and  bug-fixing & Cache-Control implementation

- hardware/include/iob-cache.vh
- hardware/src/cache-memory.v
- hardware/src/front-end.v
- hardware/src/iob-cache-axi.v
- hardware/src/iob-cache.v
- hardware/src/write-channel-axi.v
- hardware/src/write-channel-native.v
- hardware/testbench/iob-cache_tb.vh
- hardware/testbench/pipeline-iob-cache_tb.v
- software/iob-cache.c
- software/iob-cache.h
Improved Back-End write-channel for both Native and AXI (reduces consecutive writes by 1 clock-cycle
Added define CTRL_IO that allows the implementation of a i/o forced invalidate signal (allowing a L1 to invalidate the L2), and a i/o for the write-buffer empty status (allowing for the L1 also return the fact the L2 is also empty). Mono-cache systems can disable this define in hardware/include/iob_cache.vh.
> Back-End Write channel improvement; CTRL_IO invalidate and wtb_empty implementation

- hardware/simulation/verilator/Makefile
- hardware/simulation/verilator/testbench.cpp
Go to hardware/simulation/verilator and do "make all" to do the simulation.
There are errors but those occur from the MEM submodule. I removed them to run the test but of course someone else should fix them. 
With the errors removed, the simulation runs and produces a vcd file, called vcd.vcd.
Extra files are generated and can be cleaned by doing "make clean".
Important note: The reason that on the Makefile lines 14 and 15 are there is because the Verilator include is really picky with the spaces between the incdir (-I) and the path. For example, if I have a path that is /dir/, I cannot do "-I /dir/", because of the extra space, I have to do "-I/dir/".
> Initial verilator simulation

- hardware/simulation/icarus/Makefile
- hardware/simulation/simulation.mk
- hardware/simulation/verilator/Makefile
It is already defined in config.mk
> remove SIMULATOR variable from icarus/ and verilator/ Makefile

- hardware/simulation/icarus/Makefile
Rebuild a.out target to avoid using an outdated file.
Current clean target does not completely solve the problem.
> Rebuild a.out target

- .gitmodules
- config.mk
- Revert repository to use single level submodule dependency
- All submodules used by this core are on the `submodule/` folder level
- Add LIB submodule
- This avoids using implicit submodules of submodules
> add(LIB): single level submodule dependency

- .github/workflows/ci.yml
- Add github action workflow for continuous integration
- The CI workflow runs the same targets as `make test` with sim, fpga
and doc separated into independent and sequential jobs
- all jobs run in sequence, even if a previous one fails
> feat(actions): Add github action workflow

- hardware/src/iob_cache_iob.v
- info.mk
Set the top module by default to iob_cache_iob to generate the ug.pdf
Note: AXI i/f is retrieved from iob_cache_axi_m_port.vh
> use iob_cache_iob top module to generate the ug.pdf; fix some doc generation issues

- .github/workflows/ci.yml
- hardware/simulation/sim_setup.mk
- hardware/simulation/simulation.mk
- hardware/src/iob_cache_write_channel.v
- copy simulation specific sources to `BUILD_DIR/hw/sim` during setup
- add simulation specific sources in `simulation.mk` to `VSRC` and to
`NOCLEAN` variable to exclude from simulation `clean` target
- this ensures that `BUILD_DIR/hw/vsrc` has no simulation specific
sources
- this pattern could be further applied to the testbench sources `*_tb.v`:
- add `*_tb.v` to be copied to `BUILD_DIR/hw/sim` during `setup` in `sim_setup.mk`
- add `*_tb.v` files to `NOCLEAN` in `simulation.mk`
> fix(sim): update LIB, sim sources to hw/sim

- hardware/src/back-end-axi.v
This is required since the file 'm_axi_m_port.vh' is already included in the 'back_end_axi.v' file and it uses macros from iob_lib.vh
> Include iob_lib.vh on back_end_axi.v

- hardware/simulation/iob_cache_sim_wrapper.v
- hardware/simulation/iob_cache_tb.cpp
- hardware/simulation/iob_cache_tb.v
- hardware/src/iob_cache.v
- hardware/src/iob_cache_axi.v
- hardware/src/iob_cache_back_end.v
- hardware/src/iob_cache_back_end_axi.v
- hardware/src/iob_cache_control.v
- hardware/src/iob_cache_front_end.v
- hardware/src/iob_cache_iob.v
- hardware/src/iob_cache_memory.v
- hardware/src/iob_cache_read_channel.v
- hardware/src/iob_cache_read_channel_axi.v
- hardware/src/iob_cache_replacement_policy.v
- hardware/src/iob_cache_write_channel.v
- hardware/src/iob_cache_write_channel_axi.v
- refactor cache hardware sources to use `clk_i` and `rst_i` as generic port names
- add missing `iob_cache_conf.vh` includes
> Update LIB Submodule

- hardware/hw_setup.mk
- iob_cache_setup.py
- software/sw_setup.mk
- Add iob_cache_setup.py file
- Do not call setup() function if module is imported by another.
- BREAKING: modified _setup.mk to match iob-uart
- Modified hw_setup.mk and sw_setup.mk file to match ones from iob-uart.
- This may break the build process for this component
- I need to investigate more about the iob-uart build process to
ensure it also works for the cache.
- These changes allow for iob-soc/build-lib to create the build directory,
but it currently does not run in simulation.
- Update LIB
> BREAKING(build-lib): modified _setup.mk to match iob-uart; add iob_cache_setup.py file

- hardware/src/iob_cache_control.v
- Add missing `else` block after the end of the `if (USE_CTRL_CNT) begin` block.
Without this, quartus would throw an error about multiple writes to  the `rdata` signal.
- Fixed tab identation for ease of readability of Verilog blocks.
> Add missing 'else' block in `iob_cache_control`

- Makefile
- iob_cache.py
New setup process no longer uses setup.mk or bootstrap.py The user calls `python3 -B ./iob_cache.py` directly to intiate the setup process (create the build dir).
Checkout the contents of the Makefile for examples.
> feat(setup): Use new setup process: Call `iob_cache.py` directly.

- iob_cache.py
Add `widths` dictionary to generate interfaces with port widths based on CACHE parameters.
> Add correct `widths` to if_gen interfaces.

- software/src/iob-cache.c
- software/src/iob-cache.h
- remove redundant software functions. These functions are already generated in iob_cache_swreg_emb.c
> fix(sw): remove redundant functions

- hardware/src/iob_cache_control.v
- iob_cache.py
The `addr_i` signal of the `iob_cache_control` component does not contain the 2 least significant bits of the register addresses.
Therefore, the reference addresses must also be shifted by 2.
The register addresses should also be separated from each other by 4, to allow the `iob_cache_control` to know which register is being written to.
Note, the `addr_i` signal does not contain the 2 least significant bits, because the front end and other components don't use them, based on the value o the parameter `FE_NBYTES_W`. If the value of this parameter changes, so will the number of least significant bits discarded. So this solution may not for all cases!
> fix(cache_control): Fix cache_control register addresses.

- hardware/src/iob_cache_memory.v
- hardware/src/iob_cache_write_channel_axi.v
Firstly, this is a great project!
I integrate IOB-Cache in my design, through simulation and find several bugs.
1. index is not a vector based on way and in write-back, it will cause malfuction.
2. in one-way cache, the write_req_o should also occur when read miss and old cache line be flushed to memory
3.  This line - assign write_req_o = req_reg_i & ~(|way_hit) & (way_select == dirty); //flush if there is not a hit, and the way selected is dirty
way_select is one-hot but dirty is not , how can compare it? please check if my modification is right.
assign write_req_o = req_reg_i & ~(|way_hit) & dirty[way_select_bin];
> Some bugs is fixed

- .gitmodules
Remove AXI submodule because IOb-SoC already has it, and cache tests only work with IOb-SoC either way.
This cache AXI submodule also causes issues with github actions, by leaving untracked changes on multiple runs.
> feat(AXI): Remove AXI submodule
