IObundle/iob-cache

hardware/simulation/iob-cache-gtkwave.gtkw, hardware/simulation/simulation.mk, hardware/src/back-end-native.v, hardware/src/cache-memory.v, hardware/testbench/iob-cache_tb.v, hardware/testbench/iob-cache_tb.vh, hardware/testbench/pipeline-iob-cache_tb.v
- Some changes to both cache-memory and back-end.
- added pipeline testbench (similar on how a pipelined architecture processor would work.
- still some data-flow problems, some signals are asserting too soon.
=> Some additional changes to cache-memory.v, added pipelined testbench.

hardware/src/replacement-policy.v
Another simple tree PLRU replacement policy.
=> Add another tree PLRU replacement policy

README.md, hardware/src/iob-cache.v, hardware/src/replacement-policy.v, hardware/testbench/rep_pol_tb.v, hardware/testbench/rep_pol_tb.vh
- cache tested in iob-soc with both picorv32 (make test-simulator and test-board-config) and ssrv (dhrystone).
=> tested and updated rep-policy

hardware/src/write-channel-axi.v
- tested and fpga implemented.
Good to go.
Write-back still needs fixes for flush/invalidation.
=> Write-channel AXI fixes (Write-Back)

config.mk, hardware/simulation/icarus/Makefile, hardware/simulation/simulation.mk, hardware/simulation/verilator/Makefile, hardware/testbench/iob-cache_tb.vh, hardware/testbench/rep_pol_tb.vh
…rilator/ makefiles; rebuild a.out when running make sim VCD=1
=> update simulation makefiles

config.mk, hardware/fpga/fpga.mk, hardware/hardware.mk
- Fix `make test-clean` target
- Fix `make test-sim` target
- passed local `make test`
- Update all submodules
=> Fix make test-clean; make test-sim; Update submodules

hardware/hardware.mk, hardware/src/cache-memory.v
- Update LIB and MEM submodules with latest master and devel branch
respectively
- Update hardware.mk accordingl
- Update iob_fifo_sync instantiation
=> update(submodules): Update LIB and MEM

.github/workflows/ci.yml, Makefile
- add continuous integration workflow via github actions
- update top level Makefile to use `iob-lib.sh` script that runs targets
for sub cores
=> feat(actions): continuous integration actions

hardware/hardware.mk, hardware/simulation/sim_setup.mk, software/software.mk
- add copied files for setup fase to `SRC` variable
- copy needed scripts from LIB submodule during setup
=> fix(setup): copy scripts, update setup target

document/doc_setup.mk, hardware/hardware.mk
- add targets to generate verilog and latex version files in
`hardware.mk` and `doc_setup.mk` respectively
=> fix(version): update LIB, generate version files

document/doc_setup.mk, hardware/hw_setup.mk, hardware/simulation/sim_setup.mk, software/sw_setup.mk
- update makefiles with new LIB/scripts path
=> fix(setup): update LIB scripts path

.github/workflows/ci.yml, config_setup.mk, hardware/hw_setup.mk
- update `CONFIG` to `CACHE_CONFIG`
=> feat: update CONFIG to CACHE_CONFIG, update LIB

iob_cache_setup.py
- The configurable main function is useful because it allows modification of arguments when called from other projects that use this component.
=> feat(setup.py): add configurable main function; add values to params, remove associated macros

iob_cache.py
Updated python class methods according to changes in PR https://github.com/IObundle/iob-lib/pull/610.
This PR should only be merged after that PR.
Check commit log for details.
=> Update python class methods according to new LIB

Makefile, hardware/simulation/sim_build.mk
- fix alongside #iobundle/iob-soc#624
=> fix(test): update sim_build.mk with tests

hardware/simulation/src/iob_cache_tb.cpp
The verilator testbench didn't work as the author had intended - no data was written to or read from the cache and it also never printed any messages like `Reading rdata=0x0 at addr=0x0: PASSED`. But the test would still pass with a "Test passed!" message. I've changed the testbench and I believe it now works as intendend.
There was one big while loop which contained four blocks: For writing, reading, incrementing counters and validating the read data. But the write and read blocks were always followed by the incrementing block, which would then set `dut->iob_valid_i = 0` before any simulation time could pass. This also caused `dut->iob_rvalid_o` to never be true and so the read data validation block was never entered. I've now changed the testbench to not use one big while loop.
=> Fixed the verilator testbench

hardware/simulation/src/iob_cache_sim_wrapper.v, hardware/simulation/src/iob_cache_tb.v, hardware/src/iob_cache_axi.v, hardware/src/iob_cache_back_end_axi.v, hardware/src/iob_cache_front_end.v, hardware/src/iob_cache_iob.v, hardware/src/iob_cache_read_channel_axi.v, hardware/src/iob_cache_write_channel_axi.v, iob_cache.py
Related to PR: https://github.com/IObundle/iob-soc/pull/884
=> Update according to new py2hwsw version; Format code.

iob_cache.py
Related to https://github.com/IObundle/py2hwsw/pull/25 and https://github.com/IObundle/iob-soc/pull/904
=> feat(dest_dir): Replace 'purpose' by 'dest_dir'

Makefile
Related to PR https://github.com/IObundle/iob-soc/pull/916
=> feat(Makefile): Remove setup.mk include

hardware/src/iob_cache_memory.v, iob_cache.py
update cache to instantiate memories after rename
related with iobundle/iob-soc#926
=> feat(mem): update memory instantiation

default.nix
Used in PR https://github.com/IObundle/iob-soc/pull/936
=> Fix default.nix; Rename fpga.sdc
